### PR TITLE
named constructors to create from pk path and pk content

### PR DESCRIPTION
**Pull request by slepic**

### CODE REVIEW

**Comment by nicodemuz** [comment]
@kissdigital-com can we merge this in? Would be great to get PHP8 support..

**Comment by slepic** [comment]
@nicodemuz I don't think that's going to happen. This PR has been open for nearly a year with no response.

You're better off with my fork. I have just tagged master as v1.0.0. We're using it in a production application so hopefully I can keep it maintained...

Just make sure you upgrade your code by using the desired named constructor, as the default constructor has been made private.

**Comment by nicodemuz** [comment]
@slepic awesome! Would be great to have it on packagist.org as well! :)

**Comment by slepic** [comment]
@nicodemuz I'm not sure if I'm allowed to do it. I don't think I can make packagist point to a fork. I would probably have to copy the package into new repository and rebrand it (change vendor name and namespace) and that's probably not entirely legal without the author's consent...

**Comment by nicodemuz** [comment]
@slepic from a legal point of view, it should be completely fine .. https://github.com/kissdigital-com/apple-sign-in-client-secret-generator/blob/master/LICENSE

**Comment by slepic** [comment]
@nicodemuz oh ok, I'll consider that

**Comment by slepic** [comment]
@nicodemuz I have created a separate [package](https://packagist.org/packages/slepic/apple-sign-in-client-secret-generator) based on this one. It has a bit different api but does the same thing using the same code. I tagged it 0.1.0, but you can consider it stable (to the degree to which kissdigital-com package is stable), I just didnt want to go for 1.0 until some code style checks and tests and a ci pipeline is added with which I didn't bother at this point...

**Comment by nicodemuz** [comment]
@slepic awesome! I think I may now need to upgrade from PHP 8.0 to 8.1! :smile:

**Comment by slepic** [comment]
@nicodemuz [0.1.2](https://github.com/slepic/php-apple-sign-in-client-secret-generator/releases/tag/0.1.2) cheers. but upgrade your php anyway :stuck_out_tongue:

**Pull request closed without merging**
